name: Portfolio CMS

on:
  pull_request:
    branches: ["main"]

  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install Deps
        run: npm i

      - name: setup environments
        run: |

          echo "HOST={{ secrets.HOST }}" >> .env
          echo "PORT={{ secrets.PORT }}" >> .env
          echo "APP_KEYS={{ secrets.APP_KEYS }}" >> .env
          echo "API_TOKEN_SALT={{ secrets.API_TOKEN_SALT }}" >> .env
          echo "ADMIN_JWT_SECRET={{ secrets.ADMIN_JWT_SECRET }}" >> .env
          echo "JWT_SECRET={{ secrets.JWT_SECRET }}" >> .env
          echo "DATABASE_HOST={{ secrets.DATABASE_HOST }}" >> .env
          echo "DATABASE_PORT={{ secrets.DATABASE_PORT }}" >> .env
          echo "DATABASE_NAME={{ secrets.DATABASE_NAME }}" >> .env
          echo "DATABASE_USERNAME={{ secrets.DATABASE_USERNAME }}" >> .env
          echo "DATABASE_PASSWORD={{ secrets.DATABASE_PASSWORD }}" >> .env
          echo "DATABASE_SSL={{ secrets.DATABASE_SSL }}" >> .env

      - name: list dir
        run: |
          ls -la

      - name: build for production
        run: npm run build

      - name: start server
        run: pm2 restart port-cms
